# **Cleaning and Manipulating Public Health Data**
##### **Alexis Ford**

## **Overview**

##### 1. Getting Started
##### 2. Importing and Preparing Data
##### 3. Filtering Data
##### 4. Exporting Data

## **1. Getting Started**

1. First, download and install anaconda on your device. The link below is a helpful resource in completing this step. If you are having trouble with this installation, please visit the Davis Library Research Hub.
(https://unc-libraries-data.github.io/Python/Setup.html)
Presumably, if you are accessing this notebook, you have completed this step.

2. Create a new file on your device to house important documents for this project (including your data set, python notebooks, and any helpful instructions). Put this file in an accessible place, like your desktop.

3. Open Anaconda Navigator, then Jupyter Lab.

4. Create a new notebook by opening a new tab in Jupyter Lab and clik "python 3" under notebook.

## **2. Importing and Preparing Your Data**

1. Gather the data that you want to clean/filter and download it to a .csv file.

2. In order to access the .csv file in python and see your data in rows and columns like we're used to, you need to import **pandas**. Pandas is a package included in python. Use the following command to import pandas:

In [3]:
import pandas as pd

3. Create a shortcut to easily access your data. First, create a name for your data that is easiest for you to remember (here, that name is df). Then, use that name in the following command:

Example: If you name it "data", you would input `data=pd.read_csv("")` , with the exact name of your data sheet in the quotations

In [4]:
df=pd.read_csv("CountyHealthData.csv")

4. To make sure that the correct data was entered, you can input the name you made for the data.

In [5]:
df

,State,Region,Division,County,FIPS,GEOID,SMS Region,Year,Premature death,Poor or fair health,...,Drug poisoning deaths,Uninsured adults,Uninsured children,Health care costs,Could not see doctor due to cost,Other primary care providers,Median household income,Children eligible for free lunch,Homicide rate,Inadequate social support
0,AK,West,Pacific,Aleutians West Census Area,2016,2016,Insuff Data,1/1/2014,NaN,0.122,...,NaN,0.374,0.250,3791.0,0.185,216.0,69192,0.127,NaN,0.287
1,AK,West,Pacific,Aleutians West Census Area,2016,2016,Insuff Data,1/1/2015,NaN,0.122,...,NaN,0.314,0.176,4837.0,0.185,254.0,74088,0.133,NaN,NaN
2,AK,West,Pacific,Anchorage Borough,2020,2020,Region 22,1/1/2014,6827.0,0.125,...,15.37,0.218,0.096,6588.0,0.119,135.0,71094,0.319,6.29,0.160
3,AK,West,Pacific,Anchorage Borough,2020,2020,Region 22,1/1/2015,6856.0,0.125,...,17.08,0.227,0.123,6582.0,0.119,148.0,76362,0.334,5.60,NaN
4,AK,West,Pacific,Bethel Census Area,2050,2050,Insuff Data,1/1/2014,13345.0,0.211,...,NaN,0.394,0.124,5860.0,0.200,169.0,41722,0.668,12.77,0.477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6104,WY,West,Mountain,Uinta County,56041,56041,Insuff Data,1/1/2015,7436.0,0.135,...,18.66,0.192,0.090,7600.0,0.123,47.0,60953,0.273,NaN,NaN
6105,WY,West,Mountain,Washakie County,56043,56043,Insuff Data,1/1/2014,6580.0,0.106,...,NaN,0.225,0.086,8202.0,0.099,47.0,49533,0.328,NaN,0.133
6106,WY,West,Mountain,Washakie County,56043,56043,Insuff Data,1/1/2015,7572.0,0.106,...,NaN,0.226,0.101,7940.0,0.099,47.0,50740,0.309,NaN,NaN
6107,WY,West,Mountain,Weston County,56045,56045,Insuff Data,1/1/2014,5633.0,0.162,...,NaN,0.201,0.084,6906.0,0.130,28.0,53665,0.232,NaN,0.171
6108,WY,West,Mountain,Weston County,56045,56045,Insuff Data,1/1/2015,7819.0,0.162,...,NaN,0.189,0.092,7238.0,0.130,28.0,59314,0.235,NaN,NaN

## **3. Filtering Your Data**

1. Examine your data and figure out what would be most useful for your research purposes to filter.

2. To filter out a certain part of a column, use the following command: `name[name["column"]=="variable you want"]`

In the example below, I am filtering the **Region** column, so that I am only seeing data from southern states.

In [6]:
df[df["Region"]=="South"]

,State,Region,Division,County,FIPS,GEOID,SMS Region,Year,Premature death,Poor or fair health,...,Drug poisoning deaths,Uninsured adults,Uninsured children,Health care costs,Could not see doctor due to cost,Other primary care providers,Median household income,Children eligible for free lunch,Homicide rate,Inadequate social support
46,AL,South,East South Central,Autauga County,1001,1001,Region 16,1/1/2014,8376.0,0.228,...,7.42,0.180,0.047,10219.0,0.156,18.0,51441,0.361,3.57,0.237
47,AL,South,East South Central,Autauga County,1001,1001,Region 16,1/1/2015,8405.0,0.228,...,8.23,0.169,0.037,9939.0,0.156,18.0,51868,0.383,4.60,NaN
48,AL,South,East South Central,Baldwin County,1003,1003,Region 16,1/1/2014,7770.0,0.127,...,14.71,0.209,0.056,9624.0,0.144,27.0,48867,0.368,4.18,0.193
49,AL,South,East South Central,Baldwin County,1003,1003,Region 16,1/1/2015,7457.0,0.127,...,15.29,0.199,0.054,9502.0,0.144,29.0,47539,0.344,4.30,NaN
50,AL,South,East South Central,Barbour County,1005,1005,Insuff Data,1/1/2014,9458.0,0.234,...,NaN,0.242,0.061,10809.0,0.169,11.0,30287,0.664,5.13,0.176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6058,WV,South,South Atlantic,Wirt County,54105,54105,Insuff Data,1/1/2015,10747.0,0.161,...,NaN,0.235,0.055,10459.0,0.131,119.0,37132,0.526,NaN,NaN
6059,WV,South,South Atlantic,Wood County,54107,54107,Region 27,1/1/2014,7944.0,0.205,...,11.03,0.222,0.044,10707.0,0.170,89.0,42065,0.433,3.29,0.178
6060,WV,South,South Atlantic,Wood County,54107,54107,Region 27,1/1/2015,8111.0,0.205,...,12.84,0.217,0.040,10355.0,0.170,96.0,41205,0.450,3.30,NaN
6061,WV,South,South Atlantic,Wyoming County,54109,54109,Region 27,1/1/2014,14864.0,0.348,...,59.77,0.213,0.050,10662.0,0.242,13.0,32880,0.513,8.29,0.242
6062,WV,South,South Atlantic,Wyoming County,54109,54109,Region 27,1/1/2015,17265.0,0.348,...,79.78,0.222,0.049,10593.0,0.242,13.0,34525,0.582,8.50,NaN

3. Just as we did for the entire dataset, we can also create a shortcut for the southern state data. To do this, use the following command, starting with what you want to name this new data:

In [7]:
South_data=df[df["Region"]=="South"]

As we see, this gives us every column of southern data, but we may not need all the columns for our data. To pull out certain columns, we will use the `.loc` function for **attributes** (state, region, etc.). If you want to pull out an **integer** (number of the columns (1,2,etc.)), you would use `.iloc.`

4. To use the .loc function, use the following command:

The general layout of this function is: `data_name.loc[row number,"column name"]`

`:` is used to show every row within the specified columns

In [12]:
South_data.loc[:,["State","Region","Uninsured adults","Preventable hospital stays","Income inequality","Infant mortality"]]

,State,Region,Uninsured adults,Preventable hospital stays,Income inequality,Infant mortality
46,AL,South,0.180,75.15,NaN,9.0
47,AL,South,0.169,79.74,4.172,8.0
48,AL,South,0.209,54.27,NaN,6.4
49,AL,South,0.199,51.36,4.417,6.4
50,AL,South,0.242,101.23,NaN,12.8
...,...,...,...,...,...,...
6058,WV,South,0.235,74.27,3.783,NaN
6059,WV,South,0.222,110.19,NaN,8.7
6060,WV,South,0.217,85.66,4.649,9.8
6061,WV,South,0.213,142.87,NaN,NaN
6062,WV,South,0.222,133.59,5.463,NaN

5. Once you have the rows you need, you can create a new data set with just that information, similar to when we filtered out a specific column. You will use the same function that you did then: `name=code ran in step 4`

In [17]:
Final_data_2=South_data.loc[:,["Region","State","Uninsured adults","Preventable hospital stays","Income inequality","Infant mortality"]]

## **4. Exporting Your Data**

In this tutorial, we will be exporting to a `.csv file`, like when we imported.

1. In order to export your data, make sure your project file is open on the left side in Jupyter Lab.

2. To export the data as a `.csv file`, use the following command:

By using the command `to_csv`, we are telling it to export the file as a .csv file.

We also use `index=False` in order to get rid of the row numbers that pandas automatically uses when we input our data.

In [18]:
Final_data_2.to_csv("Final_data_2.csv", index=False)

You have officially imported, cleaned, filtered, and exported your data!